//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class BookIssue2
    {
        public int lid { get; set; }
        [Display(Name ="ID")]
        public string Senrollment {get; set; }
        [Display(Name = "Book Isbn")]
        public string Book_isbn { get; set; }
        [Display(Name = "Issue Date")]
        public string issue_date { get; set; }
        [Display(Name = "Return date")]
        public string Return_date { get; set; }
        [Display(Name = "Username")]
        public string Susername { get; set; }
        [Display(Name = "Status")]
        public string is_book_return { get; set; }
    }
}
