//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book2
    {
        public int Bid { get; set; }
        public string Book_title { get; set; }
        public string Book_arthor { get; set; }
        public byte[] Book_image { get; set; }
        public string Book_isbn { get; set; }
        public int Quantity { get; set; }
    }
}
