//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Student
    {
        public int id { get; set; }
        [Required(ErrorMessage ="Name can't be empty")]
        [Display(Name ="Student Name")]
        public string name { get; set; }
        [DataType(DataType.Password)]
        public string password { get; set;}
        [Required(ErrorMessage ="ID can't be empty")]
        [Display(Name ="ID")]
        public string enrollment { get; set; }
        [RegularExpression(".+@.+\\..+",ErrorMessage ="Email format not Correct")]
        [Display(Name = "Email: ")]
        public string email { get; set; }
        [Display(Name = "Contact")]
        public string contact { get; set; }
        [Display(Name = "Adress")]
        public string address { get; set; }
    }
}
