//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        [Required(ErrorMessage ="give User name") ]
        [Display(Name ="USER NAME: ")]
        public string Username { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string password { get; set; }
        public int ID { get; set; }
    }
}
